spring:
  datasource:
    url: jdbc:h2:file:./data/v360db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false
